Traceback (most recent call last):
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/lockfile/pidlockfile.py", line 77, in acquire
    write_pid_to_pidfile(self.path)
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/lockfile/pidlockfile.py", line 161, in write_pid_to_pidfile
    pidfile_fd = os.open(pidfile_path, open_flags, open_mode)
FileExistsError: [Errno 17] File exists: '/Users/klaudialegutko/Projects/airflow-tutorial/airflow/airflow-webserver-monitor.pid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/bin/airflow", line 37, in <module>
    args.func(args)
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 976, in webserver
    with ctx:
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/daemon/daemon.py", line 397, in __enter__
    self.open()
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/daemon/daemon.py", line 389, in open
    self.pidfile.__enter__()
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/daemon/pidfile.py", line 60, in acquire
    super(TimeoutPIDLockFile, self).acquire(timeout, *args, **kwargs)
  File "/Users/klaudialegutko/Projects/airflow-tutorial/venv/lib/python3.7/site-packages/lockfile/pidlockfile.py", line 88, in acquire
    self.path)
lockfile.AlreadyLocked: /Users/klaudialegutko/Projects/airflow-tutorial/airflow/airflow-webserver-monitor.pid is already locked
